/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.eci.arsw.guassap.view;

import edu.eci.arsw.guassap.messaging.MessageProducer;
import java.util.Observable;
import java.util.Observer;
import javax.swing.*;

/**
 *
 * @author hcadavid
 */
public class GuassapMainFrame extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form GuassapMainFrame
     */
    public GuassapMainFrame() {
        initComponents();
    }
    
    
    private MessageProducer msgProducer=null;

    public void setMsgProducer(MessageProducer msgProducer) {
        this.msgProducer = msgProducer;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        clientid = new javax.swing.JTextField();
        conversationtp = new javax.swing.JTabbedPane();
        jLabel2 = new javax.swing.JLabel();
        destinatario = new javax.swing.JTextField();
        msgSend = new javax.swing.JButton();
        mensajesp = new javax.swing.JScrollPane();
        mensaje = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mi ID");

        clientid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientidActionPerformed(evt);
            }
        });

        jLabel2.setText("Destinatario:");

        msgSend.setText("Enviar");
        msgSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgSendActionPerformed(evt);
            }
        });

        mensaje.setColumns(20);
        mensaje.setRows(5);
        mensajesp.setViewportView(mensaje);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(conversationtp)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(clientid, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(destinatario))
                            .addComponent(mensajesp, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(msgSend)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(clientid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(conversationtp, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(destinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensajesp)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 32, Short.MAX_VALUE)
                        .addComponent(msgSend)
                        .addGap(32, 32, 32)))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientidActionPerformed

    private void msgSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgSendActionPerformed
        msgProducer.sendMessages(this.mensaje.getText());
    }//GEN-LAST:event_msgSendActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clientid;
    private javax.swing.JTabbedPane conversationtp;
    private javax.swing.JTextField destinatario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextArea mensaje;
    private javax.swing.JScrollPane mensajesp;
    private javax.swing.JButton msgSend;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
	String text = (String)arg;
        addFromConversation(clientid.getText(),destinatario.getText(),text);
    }

    public JScrollPane createTabPane(String to) {
	   JTextArea conversation = new JTextArea();
           conversation.setColumns(20);
           conversation.setRows(5);
	   JScrollPane sp = new JScrollPane();
           sp.setViewportView(conversation);
	   conversationtp.addTab(to,null,sp);
	   return sp;
    }

    private void addConversation(String tab,String text) {
	   int idx = conversationtp.indexOfTab(tab);
           JScrollPane sp;
	   if (idx != -1) {
	     sp = (JScrollPane)conversationtp.getComponentAt(idx);
	   } else { 
             sp = createTabPane(tab);
	   }
           JViewport viewport = sp.getViewport(); 
	   JTextArea ta = (JTextArea)viewport.getView(); 
           ta.setText(ta.getText()+"\n"+(String)text);
    }

    public void addFromConversation(String from,String to,String text) {
	   addConversation(to,">> "+text);
    }

    public void addToConversation(String from,String to,String text) {
	   addConversation(to,"<< "+text);
    }
}
